on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    name: deploy to github page
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        bun_version: ['1.0.7']
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bun ${{ matrix.bun_version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun_version }}

      - name: Install dependencies
        run: bun install

      - name: Build and Deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          bun run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
