name: Deploy static content to Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    permissions:
      contents: write
    strategy:
      matrix:
        bun_version: [1.0.7]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bun ${{ matrix.bun_version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun_version }}

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build -- '--base=/${REPOSITORY_NAME}/'
        env:
          REPOSITORY_NAME: ${{ github.event.repository.name }}

      - name: Deploy
        run: |
          git config --global user.name ${USER_NAME}
          git config --global user.email ${USER_EMAIL}
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          bun run deploy
        env:
          USER_NAME: "github-actions-bot"
          USER_EMAIL: "github-actions-bot@users.noreply.github.com"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
